---
# PURE RANDOMSEARCH################################################################################################### #
randomsearch:
  optimizer: randomsearch

# DEHB ############################################################################################################### #
dehb:
  optimizer: dehb
  # Options for strategy:
  # ['rand1_bin', 'rand2_bin', 'rand2dir_bin', 'best1_bin', 'best2_bin', 'currenttobest1_bin', 'randtobest1_bin',
  # 'rand1_exp', 'rand2_exp', 'rand2dir_exp', 'best1_exp', 'best2_exp', 'currenttobest1_exp', 'randtobest1_exp']
  strategy: rand1_bin
  mutation_factor: 0.5
  crossover_prob: 0.5
  gens: 1
  eta: 3
  # Options for async_strategy: ['deferred', 'immediate', 'random', 'worst']
  async_strategy: immediate

# DRAGONFLY DEFAULT ################################################################################################## #
dragonfly_default:
  optimizer: dragonfly
  init_iter_per_dim: 10
  init_capital_frac: 0.1 # Ignored since 'init_iter_per_dim' is present

# DRAGONFLY REALTIME ################################################################################################# #
dragonfly_realtime:
  optimizer: dragonfly
  init_capital_frac: 0.1

# SMAC HYPERBAND ##################################################################################################### #
smac_hb_eta_1:
  optimizer: smac_hb
  eta: 1

# learna | metalearna
smac_hb_eta_2_learna:
  optimizer: smac_hb
  eta: 2

smac_hb_eta_2:
  optimizer: smac_hb
  eta: 2

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
smac_hb_eta_3:
  optimizer: smac_hb
  eta: 3
  max_stages: 4

# SMAC SUCCESSIVE HALVING ############################################################################################ #
smac_sh_eta_1:
  optimizer: smac_hb
  eta: 1

# learna | metalearna
smac_sh_eta_2_learna:
  optimizer: smac_sh
  eta: 2

smac_sh_eta_2:
  optimizer: smac_sh
  eta: 2

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
smac_sh_eta_3:
  optimizer: smac_sh
  eta: 3

# HPBANDSTER BOHB #################################################################################################### #
# learna | metalearna
hpbandster_bohb_eta_2_learna:
  optimizer: hpbandster_bohb
  eta: 2

hpbandster_bohb_eta_2:
  optimizer: hpbandster_bohb
  eta: 2

hpbandster_bohb_eta_3_test:
  optimizer: hpbandster_bohb
  eta: 3
  num_iterations: 1

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
hpbandster_bohb_eta_3:
  optimizer: hpbandster_bohb
  eta: 3
  max_stages: 4

# HPBANDSTER RANDOMSEARCH ############################################################################################ #
# learna | metalearna
hpbandster_rs_eta_2_learna:
  optimizer: hpbandster_rs
  eta: 2

hpbandster_rs_eta_2:
  optimizer: hpbandster_rs
  eta: 2

hpbandster_rs_eta_3_test:
  optimizer: hpbandster_rs
  eta: 3
  num_iterations: 1

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
hpbandster_rs_eta_3:
  optimizer: hpbandster_rs
  eta: 3

# HPBANDSTER HYPERBAND ############################################################################################### #
# learna | metalearna
hpbandster_hb_eta_2_learna:
  optimizer: hpbandster_hb
  eta: 2

hpbandster_hb_eta_2:
  optimizer: hpbandster_hb
  eta: 2

hpbandster_hb_eta_3_test:
  optimizer: hpbandster_hb
  eta: 3
  num_iterations: 1

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
hpbandster_hb_eta_3:
  optimizer: hpbandster_hb
  eta: 3

# HPBANDSTER H2BO #################################################################################################### #
# learna | metalearna
hpbandster_h2bo_eta_2_learna:
  optimizer: hpbandster_h2bo
  eta: 2

hpbandster_h2bo_eta_2:
  optimizer: hpbandster_h2bo
  eta: 2

hpbandster_h2bo_eta_3_test:
  optimizer: hpbandster_h2bo
  eta: 3
  num_iterations: 1

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
hpbandster_h2bo_eta_3:
  optimizer: hpbandster_h2bo
  eta: 3

...
