---
# PURE RANDOMSEARCH################################################################################################### #
randomsearch:
  optimizer: randomsearch

# DRAGONFLY DEFAULT ################################################################################################## #
dragonfly_default:
  optimizer: dragonfly
  type: default
  init_capital_frac: 0.1 # Fraction of total budget

# DRAGONFLY FOR TABULAR BENCHMARKS ################################################################################### #
dragonfly_tabular:
  optimizer: dragonfly
  type: tabular
  num_init_eval: 10 # Number of iterations

# SMAC ##################################################################################################### #
smac_hb_eta_3:
  optimizer: smac_hb
  eta: 3
  max_stages: 5

smac_sh_eta_3:
  optimizer: smac_sh
  eta: 3
  max_stages: 5

smac_hb_eta_2:
  optimizer: smac_hb
  eta: 2
  max_stages: 5

smac_sh_eta_2:
  optimizer: smac_sh
  eta: 2
  max_stages: 5

# HPBANDSTER BOHB #################################################################################################### #
hpbandster_bohb_eta_3:
  optimizer: hpbandster_bohb
  eta: 3
  max_stages: 5

hpbandster_bohb_eta_2:
  optimizer: hpbandster_bohb
  eta: 2
  max_stages: 5

hpbandster_hb_eta_3:
  optimizer: hpbandster_hb
  eta: 3
  max_stages: 5

hpbandster_hb_eta_2:
  optimizer: hpbandster_hb
  eta: 2
  max_stages: 5

hpbandster_sh_eta_3:
  optimizer: hpbandster_sh
  eta: 3
  max_stages: 5

hpbandster_sh_eta_2:
  optimizer: hpbandster_sh
  eta: 2
  max_stages: 5

...
