lr_10101:
  bench_args:
    model: lr
    task_id: 10101
  cutoff_in_s: 1205.6600931854248
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 1205.6600931854248
lr_10101_raw:
  bench_args:
    model: lr
    task_id: 10101
  cutoff_in_s: 1205.6600931854248
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 1205.6600931854248
lr_12:
  bench_args:
    model: lr
    task_id: 12
  cutoff_in_s: 20217.547069385528
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 20217.547069385528
lr_12_raw:
  bench_args:
    model: lr
    task_id: 12
  cutoff_in_s: 20217.547069385528
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 20217.547069385528
lr_146212:
  bench_args:
    model: lr
    task_id: 146212
  cutoff_in_s: 102022.12632611085
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 102022.12632611085
lr_146212_raw:
  bench_args:
    model: lr
    task_id: 146212
  cutoff_in_s: 102022.12632611085
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 102022.12632611085
lr_146606:
  bench_args:
    model: lr
    task_id: 146606
  cutoff_in_s: 91135.74319601059
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 91135.74319601059
lr_146606_raw:
  bench_args:
    model: lr
    task_id: 146606
  cutoff_in_s: 91135.74319601059
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 91135.74319601059
lr_146818:
  bench_args:
    model: lr
    task_id: 146818
  cutoff_in_s: 1257.3456539001463
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 1257.3456539001463
lr_146818_raw:
  bench_args:
    model: lr
    task_id: 146818
  cutoff_in_s: 1257.3456539001463
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 1257.3456539001463
lr_146821:
  bench_args:
    model: lr
    task_id: 146821
  cutoff_in_s: 4586.418139770508
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 4586.418139770508
lr_146821_raw:
  bench_args:
    model: lr
    task_id: 146821
  cutoff_in_s: 4586.418139770508
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 4586.418139770508
lr_146822:
  bench_args:
    model: lr
    task_id: 146822
  cutoff_in_s: 7437.024947990418
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 7437.024947990418
lr_146822_raw:
  bench_args:
    model: lr
    task_id: 146822
  cutoff_in_s: 7437.024947990418
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 7437.024947990418
lr_14965:
  bench_args:
    model: lr
    task_id: 14965
  cutoff_in_s: 49612.35265416336
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 49612.35265416336
lr_14965_raw:
  bench_args:
    model: lr
    task_id: 14965
  cutoff_in_s: 49612.35265416336
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 49612.35265416336
lr_167119:
  bench_args:
    model: lr
    task_id: 167119
  cutoff_in_s: 49357.75814612961
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 49357.75814612961
lr_167119_raw:
  bench_args:
    model: lr
    task_id: 167119
  cutoff_in_s: 49357.75814612961
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 49357.75814612961
lr_167120:
  bench_args:
    model: lr
    task_id: 167120
  cutoff_in_s: 82830.4145855217
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 82830.4145855217
lr_167120_raw:
  bench_args:
    model: lr
    task_id: 167120
  cutoff_in_s: 82830.4145855217
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 82830.4145855217
lr_168911:
  bench_args:
    model: lr
    task_id: 168911
  cutoff_in_s: 7129.8546165466305
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 7129.8546165466305
lr_168911_raw:
  bench_args:
    model: lr
    task_id: 168911
  cutoff_in_s: 7129.8546165466305
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 7129.8546165466305
lr_168912:
  bench_args:
    model: lr
    task_id: 168912
  cutoff_in_s: 3528.9894414253235
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 3528.9894414253235
lr_168912_raw:
  bench_args:
    model: lr
    task_id: 168912
  cutoff_in_s: 3528.9894414253235
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 3528.9894414253235
lr_3:
  bench_args:
    model: lr
    task_id: 3
  cutoff_in_s: 3185.5873036079406
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 3185.5873036079406
lr_31:
  bench_args:
    model: lr
    task_id: 31
  cutoff_in_s: 1503.8973586196898
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 1503.8973586196898
lr_31_raw:
  bench_args:
    model: lr
    task_id: 31
  cutoff_in_s: 1503.8973586196898
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 1503.8973586196898
lr_3917:
  bench_args:
    model: lr
    task_id: 3917
  cutoff_in_s: 1852.2028477554322
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 1852.2028477554322
lr_3917_raw:
  bench_args:
    model: lr
    task_id: 3917
  cutoff_in_s: 1852.2028477554322
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 1852.2028477554322
lr_3_raw:
  bench_args:
    model: lr
    task_id: 3
  cutoff_in_s: 3185.5873036079406
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 3185.5873036079406
lr_53:
  bench_args:
    model: lr
    task_id: 53
  cutoff_in_s: 3773.42889396286
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 3773.42889396286
lr_53_raw:
  bench_args:
    model: lr
    task_id: 53
  cutoff_in_s: 3773.42889396286
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 3773.42889396286
lr_7592:
  bench_args:
    model: lr
    task_id: 7592
  cutoff_in_s: 85300.87108663177
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 85300.87108663177
lr_7592_raw:
  bench_args:
    model: lr
    task_id: 7592
  cutoff_in_s: 85300.87108663177
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 85300.87108663177
lr_9952:
  bench_args:
    model: lr
    task_id: 9952
  cutoff_in_s: 3414.5810439910892
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 3414.5810439910892
lr_9952_raw:
  bench_args:
    model: lr
    task_id: 9952
  cutoff_in_s: 3414.5810439910892
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 3414.5810439910892
lr_9977:
  bench_args:
    model: lr
    task_id: 9977
  cutoff_in_s: 82985.1355976944
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 82985.1355976944
lr_9977_raw:
  bench_args:
    model: lr
    task_id: 9977
  cutoff_in_s: 82985.1355976944
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 82985.1355976944
lr_9981:
  bench_args:
    model: lr
    task_id: 9981
  cutoff_in_s: 28206.732478492737
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 28206.732478492737
lr_9981_raw:
  bench_args:
    model: lr
    task_id: 9981
  cutoff_in_s: 28206.732478492737
  import_benchmark: LRBenchmarkMF
  import_from: ml
  is_surrogate: false
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 28206.732478492737
