nn_10101:
  bench_args:
    task_id: 10101
  cutoff_in_s: 31734.0
  import_benchmark: NNBenchmarkMF
  import_from: ml_mmfb.nn_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 31734.0
nn_146818:
  bench_args:
    task_id: 146818
  cutoff_in_s: 19659.0
  import_benchmark: NNBenchmarkMF
  import_from: ml_mmfb.nn_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 19659.0
nn_146821:
  bench_args:
    task_id: 146821
  cutoff_in_s: 51127.0
  import_benchmark: NNBenchmarkMF
  import_from: ml_mmfb.nn_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 51127.0
nn_31:
  bench_args:
    task_id: 31
  cutoff_in_s: 32009.0
  import_benchmark: NNBenchmarkMF
  import_from: ml_mmfb.nn_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 32009.0
nn_3917:
  bench_args:
    task_id: 3917
  cutoff_in_s: 88413.0
  import_benchmark: NNBenchmarkMF
  import_from: ml_mmfb.nn_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 88413.0
nn_53:
  bench_args:
    task_id: 53
  cutoff_in_s: 29040.0
  import_benchmark: NNBenchmarkMF
  import_from: ml_mmfb.nn_benchmark
  is_surrogate: true
  main_fidelity: iter
  mem_limit_in_mb: 6000
  time_limit_in_s: 29040.0
