svm_10101:
  bench_args:
    model: svm
    task_id: 10101
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_12:
  bench_args:
    model: svm
    task_id: 12
  cutoff_in_s: 240.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 240.0
svm_146195:
  bench_args:
    model: svm
    task_id: 146195
  cutoff_in_s: 1337443.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 1337443.0
svm_146212:
  bench_args:
    model: svm
    task_id: 146212
  cutoff_in_s: 42737.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 42737.0
svm_146606:
  bench_args:
    model: svm
    task_id: 146606
  cutoff_in_s: 1569619.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 1569619.0
svm_146818:
  bench_args:
    model: svm
    task_id: 146818
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_146821:
  bench_args:
    model: svm
    task_id: 146821
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_146822:
  bench_args:
    model: svm
    task_id: 146822
  cutoff_in_s: 125.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 125.0
svm_14965:
  bench_args:
    model: svm
    task_id: 14965
  cutoff_in_s: 69099.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 69099.0
svm_167119:
  bench_args:
    model: svm
    task_id: 167119
  cutoff_in_s: 54530.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 54530.0
svm_167120:
  bench_args:
    model: svm
    task_id: 167120
  cutoff_in_s: 1062679.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 1062679.0
svm_168329:
  bench_args:
    model: svm
    task_id: 168329
  cutoff_in_s: 246227.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 246227.0
svm_168330:
  bench_args:
    model: svm
    task_id: 168330
  cutoff_in_s: 2543596.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 2543596.0
svm_168331:
  bench_args:
    model: svm
    task_id: 168331
  cutoff_in_s: 1917776.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 1917776.0
svm_168335:
  bench_args:
    model: svm
    task_id: 168335
  cutoff_in_s: 1633199.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 1633199.0
svm_168868:
  bench_args:
    model: svm
    task_id: 168868
  cutoff_in_s: 718155.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 718155.0
svm_168908:
  bench_args:
    model: svm
    task_id: 168908
  cutoff_in_s: 25861.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 25861.0
svm_168909:
  bench_args:
    model: svm
    task_id: 168909
  cutoff_in_s: 157575.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 157575.0
svm_168910:
  bench_args:
    model: svm
    task_id: 168910
  cutoff_in_s: 47573.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 47573.0
svm_168911:
  bench_args:
    model: svm
    task_id: 168911
  cutoff_in_s: 428.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 428.0
svm_168912:
  bench_args:
    model: svm
    task_id: 168912
  cutoff_in_s: 513.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 513.0
svm_3:
  bench_args:
    model: svm
    task_id: 3
  cutoff_in_s: 252.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 252.0
svm_31:
  bench_args:
    model: svm
    task_id: 31
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_3917:
  bench_args:
    model: svm
    task_id: 3917
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_53:
  bench_args:
    model: svm
    task_id: 53
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_7592:
  bench_args:
    model: svm
    task_id: 7592
  cutoff_in_s: 369874.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 369874.0
svm_9952:
  bench_args:
    model: svm
    task_id: 9952
  cutoff_in_s: 403.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 403.0
svm_9977:
  bench_args:
    model: svm
    task_id: 9977
  cutoff_in_s: 254885.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 254885.0
svm_9981:
  bench_args:
    model: svm
    task_id: 9981
  cutoff_in_s: 180.0
  import_benchmark: TabularBenchmark
  import_from: ml.tabular_benchmark
  is_surrogate: true
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 180.0
svm_10101_raw:
  bench_args:
    model: svm
    task_id: 10101
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_12_raw:
  bench_args:
    model: svm
    task_id: 12
  cutoff_in_s: 240.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 240.0
svm_146212_raw:
  bench_args:
    model: svm
    task_id: 146212
  cutoff_in_s: 42737.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 42737.0
svm_146606_raw:
  bench_args:
    model: svm
    task_id: 146606
  cutoff_in_s: 342000.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 342000.0
svm_146818_raw:
  bench_args:
    model: svm
    task_id: 146818
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_146821_raw:
  bench_args:
    model: svm
    task_id: 146821
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_146822_raw:
  bench_args:
    model: svm
    task_id: 146822
  cutoff_in_s: 125.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 125.0
svm_14965_raw:
  bench_args:
    model: svm
    task_id: 14965
  cutoff_in_s: 69099.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 69099.0
svm_167119_raw:
  bench_args:
    model: svm
    task_id: 167119
  cutoff_in_s: 54530.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 54530.0
svm_167120_raw:
  bench_args:
    model: svm
    task_id: 167120
  cutoff_in_s: 342000.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 342000.0
svm_168911_raw:
  bench_args:
    model: svm
    task_id: 168911
  cutoff_in_s: 428.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 428.0
svm_168912_raw:
  bench_args:
    model: svm
    task_id: 168912
  cutoff_in_s: 513.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 513.0
svm_31_raw:
  bench_args:
    model: svm
    task_id: 31
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_3917_raw:
  bench_args:
    model: svm
    task_id: 3917
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_3_raw:
  bench_args:
    model: svm
    task_id: 3
  cutoff_in_s: 252.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 252.0
svm_53_raw:
  bench_args:
    model: svm
    task_id: 53
  cutoff_in_s: 120.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 120.0
svm_7592_raw:
  bench_args:
    model: svm
    task_id: 7592
  cutoff_in_s: 342000.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 342000.0
svm_9952_raw:
  bench_args:
    model: svm
    task_id: 9952
  cutoff_in_s: 403.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 403.0
svm_9977_raw:
  bench_args:
    model: svm
    task_id: 9977
  cutoff_in_s: 254885.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 254885.0
svm_9981_raw:
  bench_args:
    model: svm
    task_id: 9981
  cutoff_in_s: 180.0
  import_benchmark: TabularBenchmark
  import_bencmark: SVMBenchmark
  import_from: ml
  is_surrogate: false
  main_fidelity: subsample
  mem_limit_in_mb: 6000
  time_limit_in_s: 180.0
